/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.haryoiro.calcformat.app;

import com.haryoiro.calcformat.cli.CliOptions;
import com.haryoiro.calcformat.config.FormatOption;
import com.haryoiro.calcformat.formatting.CalcFormatter;
import com.haryoiro.calcformat.cli.CliOptionParser;
import static com.haryoiro.calcformat.utils.IoUtils.pathToFile;
import static java.lang.System.exit;

public class App {

    static FormatOption formatOption = new FormatOption();

    public static void main(String[] args) {

        CliOptionParser parser = new CliOptionParser(args);
        CliOptions opt = parser.parse();
        if (opt == null) {
            CliOptionParser.printHelp();
            exit(0);
        }

        // オプションファイルが指定されていれば、フォーマットオプションを読み込む
        if (opt.getOptionFile() != null) {
            formatOption = formatOption.fromPath(opt.getOptionFile());
        }

        // 指定されたすべてのファイルに対してフォーマットをかける
        if (opt.getInputFiles() != null) {
            for (String file : opt.getInputFiles()) {
                System.out.println(CalcFormatter.format(pathToFile(file), formatOption));
            }
        }

    }

}
