/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.haryoiro.app;

import com.haryoiro.config.FormatOption;
import com.haryoiro.formatting.CalcFormatter;
import com.haryoiro.cli.CmdAttributes;
import com.haryoiro.cli.CmdOptions;
import static com.haryoiro.utils.IoUtils.pathToFile;
import static java.lang.System.exit;

public class App {

    static FormatOption formatOption = new FormatOption();

    public static void main(String[] args) {

        CmdAttributes opt = CmdOptions.parseArgs(args);
        if (opt == null) {
            CmdOptions.printHelp();
            exit(0);
        }


        if (opt.isFix()) {
            System.out.println("fix");
        }
        if (opt.isCheck()) {
            System.out.println("check");
        }
        if (opt.getOptionFile() != null) {
            formatOption = formatOption.fromPath(opt.getOptionFile());
        }

        // 指定されたすべてのファイルに対してフォーマットをかける
        if (opt.getInputFiles() != null) {
            for (String file : opt.getInputFiles()) {
                System.out.println(CalcFormatter.format(pathToFile(file), formatOption));
            }
        }

    }

}
