/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package antlr.twirl;

import org.junit.jupiter.api.Test;
import calcparser.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();


    }
}
