name: Create a pull request for release.

on:
  push:
    branches: [ develop ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if pr exists
        id: check_pr
        run: |
          echo "::set-output name=count::$(gh pr list -S develop' in:title' -B main | wc -l)"
          echo "::set-output name=pr_title::develop"
          echo "::set-output name=base_branch::main"
      - name: Create release pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B ${{ steps.check_pr.outputs.base_branch }} -t ${{ steps.check_pr.outputs.pr_title }} -b ""